#!/usr/bin/env python3
"""
Build a MITRE ATT&CK Navigator layer from the rules (and results, if present).

Open https://mitre-attack.github.io/attack-navigator/ -> "Open Existing Layer"
-> "Upload from local" and choose navigator/coverage_layer.json.

Colors: green = detected in testing, red = rule missed, yellow = rule written but
no attack data yet, orange = detected but has false positives.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sigma_lite import load_rules  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
COLORS = {"detected": "#31a354", "noisy": "#fd8d3c", "missed": "#de2d26", "untested": "#fed976"}
RANK = {"missed": 3, "noisy": 2, "untested": 1, "detected": 0}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", type=Path, default=ROOT / "results.json")
    ap.add_argument("--out", type=Path, default=ROOT / "navigator" / "coverage_layer.json")
    args = ap.parse_args()

    by_id = {}
    if args.results.exists():
        by_id = {r["id"]: r for r in json.loads(args.results.read_text())["rules"]}

    techniques: dict[str, dict] = {}
    for rule in load_rules(ROOT / "rules"):
        r = by_id.get(rule.id)
        state = "untested"
        if r:
            state = r["status"]
            if state == "detected" and r["false_positive_hits"]:
                state = "noisy"
        for t in rule.techniques:
            entry = techniques.setdefault(t, {"state": state, "titles": []})
            entry["titles"].append(rule.title)
            if RANK[state] > RANK[entry["state"]]:  # worst state wins
                entry["state"] = state

    layer = {
        "name": "LOLBin Detection Lab coverage",
        "versions": {"layer": "4.5", "navigator": "5.1.0"},
        "domain": "enterprise-attack",
        "description": "Generated by scripts/build_navigator.py",
        "techniques": [
            {
                "techniqueID": t,
                "color": COLORS[e["state"]],
                "comment": f"{e['state']}: " + "; ".join(e["titles"]),
                "enabled": True,
                "showSubtechniques": True,
            }
            for t, e in sorted(techniques.items())
        ],
        "legendItems": [
            {"label": "Detected in testing", "color": COLORS["detected"]},
            {"label": "Detected, has false positives", "color": COLORS["noisy"]},
            {"label": "Rule missed", "color": COLORS["missed"]},
            {"label": "Rule written, not yet tested", "color": COLORS["untested"]},
        ],
        "hideDisabled": False,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(layer, indent=2), encoding="utf-8")
    print(f"wrote {args.out.relative_to(ROOT)} with {len(techniques)} techniques")
    return 0


if __name__ == "__main__":
    sys.exit(main())
